# Generated by Django 4.2.13 on 2024-07-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_life_recycling_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recyclable_items',
            old_name='catergory',
            new_name='category',
        ),
    ]
