# Generated by Django 4.2.13 on 2024-07-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_life_recycling_api', '0003_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='category_name',
        ),
    ]
