# Generated by Django 4.1.3 on 2024-07-15 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_life_recycling_api', '0003_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclable_items',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_life_recycling_api.user'),
        ),
    ]
