# Generated by Django 4.2.13 on 2024-07-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_life_recycling_api', '0004_rename_name_categories_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclable_items',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='recyclable_items',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='second_life_recycling_api.vendors'),
        ),
    ]
