# Generated by Django 4.1.3 on 2024-07-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_life_recycling_api', '0004_alter_recyclable_items_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recyclable_items',
            old_name='user_id',
            new_name='user',
        ),
    ]
