# Generated by Django 4.1.3 on 2024-07-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "second_life_recycling_api",
            "0005_remove_recyclable_items_pickup_location_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="admin",
            field=models.BooleanField(default=True),
        ),
    ]
