# Generated by Django 4.1.3 on 2024-07-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_life_recycling_api', '0006_rename_user_id_shopping_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
