# Generated by Django 4.1.3 on 2024-07-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "second_life_recycling_api",
            "0008_cartitem_company_recyclableitem_shoppingcart_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingcart",
            name="total",
        ),
    ]
