# Generated by Django 4.1.3 on 2024-07-19 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_life_recycling_api', '0008_alter_cartitem_cart_alter_cartitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='second_life_recycling_api.shopping_cart'),
        ),
    ]
