# Generated by Django 4.1.3 on 2024-07-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_life_recycling_api', '0009_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='total',
        ),
    ]
