# Generated by Django 4.1.3 on 2024-05-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Gamer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50)),
                ("bio", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Gametype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("maker", models.CharField(max_length=50)),
                ("number_of_players", models.IntegerField()),
                ("skill_level", models.IntegerField()),
                (
                    "game_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="levelupapi.gametype",
                    ),
                ),
                (
                    "gamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="levelupapi.gamer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventGamer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="levelupapi.event",
                    ),
                ),
                (
                    "gamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="levelupapi.gamer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="levelupapi.game"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="levelupapi.gamer"
            ),
        ),
    ]
