# Generated by Django 4.1.3 on 2024-07-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("levelupapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Recyclable_Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("pickup_location", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image_url", models.CharField(max_length=100)),
                ("user_id", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("catergory_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shopping_Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("item_id", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status", models.CharField(max_length=50)),
                ("total", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("photo", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("uid", models.CharField(max_length=50)),
                ("admin", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Gamer",
        ),
    ]
