# Generated by Django 4.1.3 on 2024-07-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("levelupapi", "0002_categories_recyclable_items_shopping_cart_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopping_cart",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name="shopping_cart",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
    ]
